### ISSUE TITLE
Satellite ions and side chain losses

### ISSUE THREAD

**Issue by douweschulte** [HUPO-PSI/mzPAF#11]
I have been reading the mzPAF format to build a parser and allow my rustyms to export mzPAF and I have the following suggestions:
- 4.4.1 Allow satellite ions as well (`dvw`) these should be handled exactly like the main series. With one caveat there are two amino acids (T and I) that have two d and w ions. These I have seen called A and B for the two different ones, the specification could specify that A is the heavier of the two and B the lighter. Eg `wa12` and `wb12` for the two different w ions for an isoleucine 12.
- 4.4.1 Write the prefix in a font that allows to discern I and l (`I and l`) and/or list the unicode character code for the prefixes.
- 4.5 Neutral losses of the side chain of amino acids are somewhat common in etd fragmentation, would it be possible to have an easy way to write that down? I suggest to add a list of all side chains to the reference molecules list. Something like `sA`/`sideA` for sidechain from Alanine.

**Comment by edeutsch** [comment]
1) My recollection is that this was suggested also once long ago, and we decided that this was sufficiently obscure and we didn't have expertise in them, and decided they could just be expressed as neutral losses of one of the more common ions. If you feel it's important and have example USIs, we might be persuaded to reconsider.

2) Very sensible, yes, we'll fix.

3) I am thinking just to use chemical formulas rather than some fancy side chain notation, but we should discuss further.

**Comment by douweschulte** [comment]
For anyone finding this. 1 and 2 are added in the specification and 3 is added to the list of reference molecules see #15.
